/*
 * File: app/view/Users/Win.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Everlast.view.Users.Win', {
    extend: 'Ext.Dialog',
    alias: 'widget.users.win',

    requires: [
        'Everlast.view.Users.WinViewModel',
        'Everlast.view.Users.Form',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'users.win'
    },
    title: 'My Dialog',

    items: [
        {
            xtype: 'users.form'
        }
    ]

});